# Plugins (managed by tpack)
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "sainnhe/tmux-fzf"

set -g status-right ''
set -g status-left '#H #S '
set -g status-left-length 100
set -g status-justify left

# Enable mouse support
set -g mouse on

# Activity bell and whistles
set -g visual-activity on

# Show titles in pane borders
set -g pane-border-status top
set -g pane-border-format " #P: #{pane_current_command} "

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically after closing one
set -g renumber-windows on

# Dim inactive panes
set -g window-style 'fg=colour244,bg=colour235'

# Keep active pane normal/bright
set -g window-active-style 'fg=colour252,bg=colour234'

# Optional: make the active border obvious too
set -g pane-border-style 'fg=colour238'
set -g pane-active-border-style 'fg=colour124'

# Set parent terminal title to reflect current window in tmux session
set -g set-titles on
set -g set-titles-string "#I:#W"

# Optional: pane titles
set -g pane-border-status top
set -g pane-border-format " #P: #{pane_current_command} "

# https://gist.github.com/jftuga/ffa03dbf4cd818f00cc32ce4186d6c1c
bind-key -n S-Enter send-keys Escape "[13;2u"
set -s extended-keys on
set -as terminal-features 'tmux-256color:extkeys'

# Initialize tpack - MUST be the last line of this file.
run "tpack init"
