# Plugins (managed by tpack)
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "sainnhe/tmux-fzf"

set -g status-right ''
set -g status-left '#H #S '
set -g status-left-length 100
set -g status-justify left

# Initialize tpack - MUST be the last line of this file.
run "tpack init"
